# This is a basic workflow exercise practice by Okereke Ugochukwu
name: GitHub Actions Demo 

# Controls when the workflow srtart
on:
# Triggers the workflow on push or pull requests
  push:
    branches: [main]
    paths-ignore: [.github/**]
  
  schedule:
    - cron: "15 6 * * 0"
    
  workflow_dispatch:
Â  jobs:

Â    Build:
Â Â Â    runs-on: ubuntu-latest
Â Â Â    steps:
    
Â Â Â Â Â  - run: | 
        echo "ðŸŽ‰ The job was triggered by event: ${{ github.event_name }}" 
        echo "ðŸ”Ž The name of your branch is ${{ github.ref }} and your repository is ."
        
Â Â Â Â Â Â - uses: actions/checkout@v3.3.0
      
Â Â Â Â Â Â - name: List files in the repository
      
Â Â Â Â Â Â - run: |
Â Â Â Â Â Â Â  echo "The repository ${{ github.repository }} contains the following files:" 
          tree
  
  
